"""empty message

Revision ID: 141a75cd647d
Revises: 4930ecb441c0
Create Date: 2016-04-05 19:41:47.419037

"""

# revision identifiers, used by Alembic.
revision = '141a75cd647d'
down_revision = '4930ecb441c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('last_modified_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'last_modified_date')
    ### end Alembic commands ###
