"""empty message

Revision ID: 193fe23d12f
Revises: 34f65c722f1
Create Date: 2014-08-23 18:01:56.166066

"""

# revision identifiers, used by Alembic.
revision = '193fe23d12f'
down_revision = '34f65c722f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'category_id')
    ### end Alembic commands ###
