"""empty message

Revision ID: 2a9e75c6bb7
Revises: 5a8bcac29a1
Create Date: 2014-08-23 18:33:22.613889

"""

# revision identifiers, used by Alembic.
revision = '2a9e75c6bb7'
down_revision = '5a8bcac29a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_nature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expense', sa.Column('frequency_id', sa.Integer(), nullable=True))
    op.add_column('expense', sa.Column('nature_id', sa.Integer(), nullable=True))
    op.add_column('expense', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'subcategory_id')
    op.drop_column('expense', 'nature_id')
    op.drop_column('expense', 'frequency_id')
    op.drop_table('expense_subcategory')
    op.drop_table('expense_nature')
    op.drop_table('expense_frequency')
    ### end Alembic commands ###
