"""empty message

Revision ID: 2d553eed14d
Revises: 193fe23d12f
Create Date: 2014-08-23 18:12:26.836443

"""

# revision identifiers, used by Alembic.
revision = '2d553eed14d'
down_revision = '193fe23d12f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
