"""empty message

Revision ID: 2fa0c8a4816
Revises: 4d5953a6c61
Create Date: 2014-08-09 12:06:58.890382

"""

# revision identifiers, used by Alembic.
revision = '2fa0c8a4816'
down_revision = '4d5953a6c61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
