"""empty message

Revision ID: 34f65c722f1
Revises: e074d31368
Create Date: 2014-08-23 17:58:36.406638

"""

# revision identifiers, used by Alembic.
revision = '34f65c722f1'
down_revision = 'e074d31368'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_category')
    ### end Alembic commands ###
