"""empty message

Revision ID: 4d500d2ac15
Revises: 2d553eed14d
Create Date: 2014-08-23 18:13:27.185345

"""

# revision identifiers, used by Alembic.
revision = '4d500d2ac15'
down_revision = '2d553eed14d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
