"""empty message

Revision ID: 4d5953a6c61
Revises: 45eebbdabae
Create Date: 2014-08-09 12:05:59.748948

"""

# revision identifiers, used by Alembic.
revision = '4d5953a6c61'
down_revision = '45eebbdabae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
