"""empty message

Revision ID: 5a8bcac29a1
Revises: 4d500d2ac15
Create Date: 2014-08-23 18:28:07.116374

"""

# revision identifiers, used by Alembic.
revision = '5a8bcac29a1'
down_revision = '4d500d2ac15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
