"""empty message

Revision ID: e074d31368
Revises: 2fa0c8a4816
Create Date: 2014-08-23 17:54:31.141528

"""

# revision identifiers, used by Alembic.
revision = 'e074d31368'
down_revision = '2fa0c8a4816'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
